openapi: 3.1.0
info:
  version: 1.0.0
  title: My Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    API for managing contacts, including creating, updating, retrieving, and deleting contact information.
tags:
  - name: Contacts
    description: API for contacts in the system
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-u9rp.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'
components:
  schemas:
    Contact:
      $ref: '../swagger/components/schemas/Contact.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    Unauthorized:
      $ref: '../swagger/components/responses/401.yaml'
    NotFound:
      $ref: '../swagger/components/responses/404.yaml'
    InternalServerError:
      $ref: '../swagger/components/responses/500.yaml'
